# This code is generated by copilot

import pytest
from source.school import Teacher, Person, Classroom, TooManyStudents

@pytest.fixture
def classroom():
    teacher = Teacher("Mr. Smith")
    students = [Person(f"Student {i}") for i in range(1, 6)]  # 5 students
    return Classroom(teacher, students, "Python 101")

def test_add_student(classroom):
    new_student = Person("New Student")
    classroom.add_student(new_student)
    assert new_student in classroom.students

def test_add_student_raises_exception(classroom):
    # Adding students until reaching the limit
    for i in range(6, 12):  # We already have 5 students
        classroom.add_student(Person(f"Student {i}"))
    new_student = Person("New Student Beyond Limit")
    with pytest.raises(TooManyStudents):
        classroom.add_student(new_student)

def test_remove_student(classroom):
    student_to_remove = classroom.students[0]
    classroom.remove_student(student_to_remove.name)
    assert student_to_remove not in classroom.students

def test_change_teacher(classroom):
    new_teacher = Teacher("Mrs. Jones")
    classroom.change_teacher(new_teacher)
    assert classroom.teacher == new_teacher

if __name__ == '__main__':
    pytest.main()
